import type { ReactNode } from "react";
import { applyGlobalStyles } from "../globalStyles";
import { getCssText } from "../seams.config";

// Apply global styles so they are included in getCssText()
applyGlobalStyles();

// getCssText() returns CSS generated by Seams at build time from our
// seams.config.ts theme tokens. This is not user-supplied content --
// it is deterministic output from our own design token configuration.
const seamsCss = getCssText();

export default async function RootElement({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <style id="seams" dangerouslySetInnerHTML={{ __html: seamsCss }} />
      </head>
      <body>{children}</body>
    </html>
  );
}

export const getConfig = async () => {
  return {
    render: "static",
  } as const;
};
